version: "3.0"
services:
  webserver:
    image: webserver
    restart: unless-stopped
    environment:
      - TZ=Europe/Minsk
    env_file:
      - .env
      - secrets.env
    ports:
      - $WEBSERVER_PORT:443
    networks:
      - default
    volumes:
      - './src/webserver:/app/webserver'
    build:
      context: .
      dockerfile: build_data/dockerfiles/webserver_dockerfile

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
      - secrets.env
    ports:
      - $DB_PORT:5432
    volumes:
      - $DB_VOLUME:/var/lib/postgresql/data
    networks:
      - default

  redis:
    image: redis
    volumes:
      - './redis:/usr/local/etc/redis'
    command:
      - 'redis-server'
      - '/usr/local/etc/redis/redis.conf'
    ports:
      - 6379:6379
    networks:
      - default


networks:
  default: null
